development:
  sessions:
    default:
      database: opensourceforwomen_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  sessions:
    default:
      database: opensourceforwomen_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
    options:
      max_retries_on_connection_failure: 20
      persist_in_safe_mode: true
      skip_version_check: true